// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOLOyqHO3Vuzy4s7OOgBDrXhsfmFLB1yI',
    appId: '1:483380386928:web:f379cc2d44210daf0728b5',
    messagingSenderId: '483380386928',
    projectId: 'merino-cizgi',
    authDomain: 'merino-cizgi.firebaseapp.com',
    storageBucket: 'merino-cizgi.firebasestorage.app',
    measurementId: 'G-PGR223THCX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAFyOvopNNAjLKB_8tizRhFgT3o3RQDPI',
    appId: '1:483380386928:ios:e1a6900af2732a1e0728b5',
    messagingSenderId: '483380386928',
    projectId: 'merino-cizgi',
    storageBucket: 'merino-cizgi.firebasestorage.app',
    androidClientId: '483380386928-09fcmvfrq522jmo10ucjq4f15lp8hj4i.apps.googleusercontent.com',
    iosClientId: '483380386928-dbsv1fpq1s4m8n7593notsi0tnqvges8.apps.googleusercontent.com',
    iosBundleId: 'com.merinocizgi.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAFyOvopNNAjLKB_8tizRhFgT3o3RQDPI',
    appId: '1:483380386928:ios:e1a6900af2732a1e0728b5',
    messagingSenderId: '483380386928',
    projectId: 'merino-cizgi',
    storageBucket: 'merino-cizgi.firebasestorage.app',
    androidClientId: '483380386928-09fcmvfrq522jmo10ucjq4f15lp8hj4i.apps.googleusercontent.com',
    iosClientId: '483380386928-dbsv1fpq1s4m8n7593notsi0tnqvges8.apps.googleusercontent.com',
    iosBundleId: 'com.merinocizgi.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN1-PyGA8INw4V_wGvOWogLzPfXuwT16c',
    appId: '1:483380386928:android:8d0cd8c9bf5760ff0728b5',
    messagingSenderId: '483380386928',
    projectId: 'merino-cizgi',
    storageBucket: 'merino-cizgi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOLOyqHO3Vuzy4s7OOgBDrXhsfmFLB1yI',
    appId: '1:483380386928:web:20d51dd35ad2c1da0728b5',
    messagingSenderId: '483380386928',
    projectId: 'merino-cizgi',
    authDomain: 'merino-cizgi.firebaseapp.com',
    storageBucket: 'merino-cizgi.firebasestorage.app',
    measurementId: 'G-4QS4CJ9DJ8',
  );

}